FROM node:14-alpine

RUN apk add libc6-compat git

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build:as-dev

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED 1

CMD ["yarn", "start:as-dev"]
