export const FARM_DESKTOP_MEDIA = '1340px'
export const FARM_LAPTOP_MEDIA = '1024px'
export const FARM_MAX_TABLET_MEDIA = '876px'
export const FARM_TABLET_MEDIA = '768px'
export const FARM_MIN_TABLET_MEDIA = '650px'
export const FARM_MOBILE_MEDIA = '550px'
