name: develop

on:
  push:
    branches:
      - develop
  #pull_request:
  #  branches:
  #    - develop

jobs:
  build:
    runs-on: [self-hosted, dev]  
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io        
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/alium-finance/alium-frontend:develop
          file: Dockerfile.develop
          cache-from: type=registry,ref=ghcr.io/alium-finance/alium-frontend:develop
          cache-to: type=inline
          build-args: APP_BSCSCAN_API_KEY=${{ secrets.APP_BSCSCAN_API_KEY }}

  deploy:
    needs: build
    runs-on: [self-hosted, dev]
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker stack deploy --compose-file docker-compose.develop.yml alium-frontend-develop --with-registry-auth
      - run: docker system prune -f
