name: master

on: workflow_dispatch

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: [self-hosted, dev]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/alium-finance/alium-frontend:master
          file: Dockerfile.master
          cache-from: type=registry,ref=ghcr.io/alium-finance/alium-frontend:master
          cache-to: type=inline
          build-args: APP_BSCSCAN_API_KEY=${{ secrets.APP_BSCSCAN_API_KEY }}

  deploy:
    needs: build
    runs-on: [self-hosted, prod]
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker stack deploy --compose-file docker-compose.master.yml alium --with-registry-auth
      - run: docker system prune -f
      - name: Purge cache
        run: ~/purgecache.sh
